
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - rm -rf node_modules package-lock.json   # 👈 clean install
      - npm install
      - chmod -R +x node_modules/.bin           # 👈 permission fix

  build:
    commands:
      - npx react-scripts build                 # 👈 IMPORTANT CHANGE

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build